#ifndef __CONFIG_H__
#define __CONFIG_H__

#define NUMBER_OF_FRAMES 30.0
#define ANIMATION_SPEED 10.0
#define WINDOW_WIDTH 1280.0
#define WINDOW_HEIGHT 720.0
#define SPRITE_WIDTH 128
#define SPRITE_HEIGHT 128
#define SPRITE_SCALE 2.5
#define FADE_SPEED 10

#endif